---
title: "Youth Football Data Analysis"
output: html_notebook
---

```{r}
#libraries
library(tidyverse)
library(googlesheets4)
library(janitor)
library(tidycensus)
#install.packages("googlesheets4")

#Authenticating with Google account
#gs4_auth()

# Load Census API key
Sys.setenv(CENSUS_API_KEY = "5cb2b9c628a1d1329c5bf4d36fe4435c6501efc8", overwrite = TRUE)

# Load ACS crosswalk
acs_2021 <- load_variables(2021, "acs5")

# Load 2020 Census crosswalk
census_2020 <- load_variables(2020, "pl", cache = TRUE)

# Helpful references for using ACS and Census APIs: #https://censusreporter.org/topics/table-codes/
#https://walker-data.com/tidycensus/articles/basic-usage.html

```

```{r}

#Load football roster scraper. Also did some cleaning for special cases here. For the players who were missing hometown information, this was obtained by looking at rosters from previous years.
football_rosters <- read_csv("football_roster.csv") %>%
  clean_names() %>%
  mutate(hometown = case_when(
    hometown == "Pompano, Beach, Fla." ~ "Pompano Beach, Fla.",
    hometown == "Livemore Calif." ~ "Livemore, Calif.",
    hometown == "Washington D.C." ~ "Washington, D.C.",
    hometown == "Tampa. Fla." ~ "Tampa, Fla.",
    hometown == "Upper Marlboro. Md." ~ "Upper Marlboro, Md.",
    hometown == "Norfolk,Va." ~ "Norfolk, Va.",
    hometown == "Bronx N.Y." ~ "Bronx, N.Y.",
    hometown == "Cocoa Fla." ~ "Cocoa, Fla.",
    hometown == "Jefferson" ~ "Jefferson Township, NJ",
    hometown == "Melbourne" ~ "Melbourne, FL",
    hometown == "Chicago" ~ "Chicago, IL",
    hometown == "Cincinnati" ~ "Cincinnati, OH",
    hometown == "Cleveland" ~ "Cleveland, OH",
    hometown == "St. Louis" ~ "St. Louis, MO",
    hometown == "Inglewood" ~ "Inglewood, CA",
    hometown == "Chatworth, Ga." ~ "Chatsworth, Ga.",
    hometown == "Kingland, Ga." ~ "Kingsland, Ga.",
    hometown == "East Cobb, GA" ~ "Marietta, GA",
    hometown == "Platville, Ala." ~ "Prattville, Ala.",
    TRUE ~ hometown)) %>%
  mutate(hometown = case_when(
    name == "Feyisayo Oluleye" ~ "Lancaster, PA",
    name == "Kyle Vaccarella" ~ "Fairfield, CT",
    TRUE ~ hometown))

#Let's also use this as a time to load a state crosswalk we'll use later
state_crosswalk <- read_csv("state_crosswalk.csv") %>%
  mutate(state_name_caps = str_to_upper(state_name)) %>%
  select(state_abb, state_name_caps)

#Let's load some hometowns that we passed through and cleaned with Open Refine
hometowns_open_refine <- read_csv("hometowns_open_refine.csv")

#Checking to see that we have 68 schools and the player counts for each school
# school_check <- football_rosters %>%
#   group_by(school) %>%
#   summarise(total_players = n()) %>%
#   arrange(total_players)

#Checking to make sure there are no duplicate players
# player_check <- football_rosters %>%
#   group_by(name, school) %>%
#   summarise(total = n()) %>%
#   arrange(desc(total))

```

```{r}

#CLEANING/STANDARDIZING STATE

#Splitting the hometown column so we can work with the state
football_rosters <- football_rosters %>%
  mutate(hometown_cleaning = hometown) %>%
  separate(hometown_cleaning, into = c("hometown_city", "hometown_state", "hometown_country"), sep = ", ")

#What kind of values are we getting in hometown_state?
state_check <- football_rosters %>%
  group_by(hometown_state) %>%
  summarise(total = n()) %>%
  arrange(hometown_state)

#Many of those aren't U.S. states. Let's make a new dataframe that only has players from the 50 states:
excluded_states <- c(" Western Australia", "Alberta", "American Samoa", "Australia", "Bahamas", "Belgium", "Canada", "China", "Colombia", "Congo", "County Kerry", "Denmark", "DR of the Congo", "England", "Finland", "France", "Gabon", "Germany", "Ghana", "Ireland", "Japan", "Manitoba", "Mexico", "N.S.", "New South Wales", "New Zealand", "Nigeria", "NSW", "Ont.", "Ontario", "QC", "Que.", "Quebec", "Québec", "Queensland", "Saskatchewan", "Serbia", "South Africa", "South Australia", "Sweden", "Switzerland", "The Netherlands", "Tonga", "United Kingdom", "Victoria", "Victoria AU", "Western Samoa")

football_rosters_usa <- football_rosters %>%
  filter(!(hometown_state %in% excluded_states) | is.na(hometown_state)) %>%
  mutate(hometown_state = case_when(
    hometown_state == "Maui" ~ "HI",
    hometown_state == "New York City" ~ "NY",
    TRUE ~ hometown_state))

#And now let's recheck those hometown_state values:
state_check_usa <- football_rosters_usa %>%
  group_by(hometown_state) %>%
  summarise(total = n()) %>%
  arrange(hometown_state)

#Let's standardize these to the state postal abbreviation:
#First, let's try removing punctuation and making everything upper case:
football_rosters_usa <- football_rosters_usa %>%
  mutate(hometown_state_first_try = str_to_upper(gsub("[[:punct:]]", "", hometown_state)))

#Second, let's see if we can use our crosswalk:
football_rosters_usa <- football_rosters_usa %>%
  left_join(state_crosswalk, by=c("hometown_state_first_try" = "state_name_caps"))

football_rosters_usa <- football_rosters_usa %>%
  rename(hometown_state_second_try = state_abb)

#Third, let's combine the results of our first two tries and check to see how much that reduced our unique values
football_rosters_usa <- football_rosters_usa %>%
  mutate(hometown_state_third_try = ifelse(is.na(hometown_state_second_try), hometown_state_first_try, hometown_state_second_try))

state_check_usa_update <- football_rosters_usa %>%
  group_by(hometown_state_third_try) %>%
  summarise(total = n()) %>%
  arrange(hometown_state_third_try)

#Now we're down to much fewer state values. Let's manually take care of the rest.
football_rosters_usa <- football_rosters_usa %>%
  mutate(hometown_state_clean = case_when(
    hometown_state_third_try == "ALA" ~ "AL",
    hometown_state_third_try == "ARIZ" ~ "AZ",
    hometown_state_third_try == "ARK" ~ "AR",
    hometown_state_third_try == "CALF" | hometown_state_third_try == "CALIF" ~ "CA",
    hometown_state_third_try == "COL" | hometown_state_third_try == "COLO" ~ "CO",
    hometown_state_third_try == "CONN" ~ "CT",
    hometown_state_third_try == "DEL" ~ "DE",
    hometown_state_third_try == "FLA" ~ "FL",
    hometown_state_third_try == "ILL" ~ "IL",
    hometown_state_third_try == "IND" ~ "IN",
    hometown_state_third_try == "KAN" ~ "KS",
    hometown_state_third_try == "MASS" ~ "MA",
    hometown_state_third_try == "MICH" ~ "MI",
    hometown_state_third_try == "MINN" ~ "MN",
    hometown_state_third_try == "MISS" ~ "MS",
    hometown_state_third_try == "MONT" ~ "MT",
    hometown_state_third_try == "NEB" ~ "NE",
    hometown_state_third_try == "NEV" ~ "NV",
    hometown_state_third_try == "OKLA" ~ "OK",
    hometown_state_third_try == "ORE" ~ "OR",
    hometown_state_third_try == "PENN" ~ "PA",
    hometown_state_third_try == "TENN" ~ "TN",
    hometown_state_third_try == "W VA" | hometown_state_third_try == "WVA" ~ "WV",
    hometown_state_third_try == "WASH" ~ "WA",
    hometown_state_third_try == "WIS" | hometown_state_third_try == "WISC" ~ "WI",
    hometown_state_third_try == "WYO" ~ "WY",
    TRUE ~ hometown_state_third_try))

#What's the final state breakdown?
football_rosters_usa_states <- football_rosters_usa %>%
  group_by(hometown_state_clean) %>%
  summarise(total_players=n()) %>%
  arrange(desc(total_players))

```

```{r}

#STATES WITH POPULATION DATA

#Let's try to add in some population data and try to figure out the number of Power 5 football players per 100,000 residents in a state
#First, let's get ourselves a dataframe that has state postal abbreviations and their most recent ACS state population:
state_pops_2021 <- get_acs(geography = "state",
                           variables = "B01003_001",
                           year = 2021)

state_pops_2021 <- state_pops_2021 %>%
  clean_names() %>%
  mutate(name_caps = str_to_upper(name)) %>%
  mutate(name_caps = case_when(
    name_caps == "DISTRICT OF COLUMBIA" ~ "WASHINGTON, DC",
    TRUE ~ name_caps
  )) %>%
  left_join(state_crosswalk, by=c("name_caps" = "state_name_caps"))

state_pops_2021 <- state_pops_2021 %>%
  select(state_abb, estimate) %>%
    filter(!is.na(state_abb)) #Removed NA value, which was Puerto Rico

# Now, let's join our population data to our state count of football players data:
football_rosters_usa_states <- football_rosters_usa_states %>%
  inner_join(state_pops_2021, by=c("hometown_state_clean" = "state_abb"))

football_rosters_usa_states <- football_rosters_usa_states %>%
  rename(total_pop = estimate)

football_rosters_usa_states <- football_rosters_usa_states %>%
  mutate(players_per_hundred_thousand = round((total_players*100000)/total_pop,1)) %>%
  arrange(desc(players_per_hundred_thousand))

# CSV
#write_csv(football_rosters_usa_states, file = "state_counts.csv")

```

```{r}

# START TO CLEAN/STANDARDIZE HOMETOWNS

# CSV - going to try cleaning this through Open Refine
#write_csv(distinct_hometowns, file = "hometowns_to_clean.csv")

#Join our Open Refine dataframe to our dataframe of Power Five players
hometowns_open_refine_modified <- hometowns_open_refine %>%
  select(hometown_city, hometown_city_clean, hometown_state_clean)

football_rosters_usa <- football_rosters_usa %>%
  left_join(hometowns_open_refine_modified, by = c("hometown_city", "hometown_state_clean"))

distinct_hometowns <- football_rosters_usa %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total = n())

#From here, the best way to continue working on this will likely be state-by-state

```

```{r}

# ALABAMA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_al <- football_rosters_usa %>%
  filter(hometown_state_clean == "AL")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_al <- football_rosters_al %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_al_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "AL",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_al_2021 <- census_data_al_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_al_2021 <- census_data_al_2021 %>%
  mutate(state = case_when(
    state == 'Alabama' ~ "AL"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_al_complete <- distinct_hometowns_al %>%
  left_join(census_data_al_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_al_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Highland Home, AL, the zip code (36041) seems to be a good substitute: https://censusreporter.org/profiles/86000US36041-36041/
census_data_highland_al_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 36041") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "AL") %>%
  mutate(city = case_when(
    city == "ZCTA5 36041" ~ "Highland Home")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# For Watson, AL, data obtained using population of nearby Brookside, AL, which seems to include Watson https://censusreporter.org/profiles/16000US0109736-brookside-al/
census_data_watson_al_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "AL",
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "Brookside town, Alabama") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "AL") %>%
  mutate(city = case_when(
    city == "Brookside town, Alabama" ~ "Watson")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_al_2021 <- bind_rows(census_data_al_2021, census_data_highland_al_2021, census_data_watson_al_2021)
 
hometowns_al_complete <- distinct_hometowns_al %>%
  left_join(census_data_al_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_al_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_al_complete, file = "hometowns_al.csv")

```

```{r}

# ARIZONA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_az <- football_rosters_usa %>%
  filter(hometown_state_clean == "AZ")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_az <- football_rosters_az %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_az_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "AZ",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_az_2021 <- census_data_az_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_az_2021 <- census_data_az_2021 %>%
  mutate(state = case_when(
    state == 'Arizona' ~ "AZ"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_az_complete <- distinct_hometowns_az %>%
  left_join(census_data_az_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_az_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

#Not applicable for Arizona

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
#Not applicable for Arizona

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_az_complete, file = "hometowns_az.csv")

```

```{r}

# FLORIDA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_fl <- football_rosters_usa %>%
  filter(hometown_state_clean == "FL")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_fl <- football_rosters_fl %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_fl_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "FL",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_fl_2021 <- census_data_fl_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_fl_2021 <- census_data_fl_2021 %>%
  mutate(state = case_when(
    state == 'Florida' ~ "FL")) %>%
    filter(city != "Plantation" | total_pop != 4565) #Removing the second Plantation, FL that is a CDP

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_fl_complete <- distinct_hometowns_fl %>%
  left_join(census_data_fl_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_fl_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Lithia, FL, the zip code (33547) seems to be a good substitute: https://censusreporter.org/profiles/86000US33547-33547/
census_data_lithia_fl_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 33547") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "FL") %>%
  mutate(city = case_when(
    city == "ZCTA5 33547" ~ "Lithia")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# For Ponte Vedra Beach, FL, the zip code (32082) seems to be a good substitute: https://censusreporter.org/profiles/86000US32082-32082/
census_data_ponte_fl_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 32082") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "FL") %>%
  mutate(city = case_when(
    city == "ZCTA5 32082" ~ "Ponte Vedra Beach")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# For Santa Rosa Beach, FL, the zip code (32459) seems to be a good substitute: https://censusreporter.org/profiles/86000US32459-32459/
census_data_santa_fl_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 32459") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "FL") %>%
  mutate(city = case_when(
    city == "ZCTA5 32459" ~ "Santa Rosa Beach")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# For St. Johns, FL, the zip code of the high school (32259) seems to be a good substitute: https://censusreporter.org/profiles/86000US32259-32259/
census_data_stjohns_fl_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 32259") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "FL") %>%
  mutate(city = case_when(
    city == "ZCTA5 32259" ~ "St. Johns")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_fl_2021 <- bind_rows(census_data_fl_2021, census_data_lithia_fl_2021, census_data_ponte_fl_2021, census_data_santa_fl_2021, census_data_stjohns_fl_2021)
 
hometowns_fl_complete <- distinct_hometowns_fl %>%
  left_join(census_data_fl_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_fl_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_fl_complete, file = "hometowns_fl.csv")

```

```{r}

# GEORGIA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_ga <- football_rosters_usa %>%
  filter(hometown_state_clean == "GA")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_ga <- football_rosters_ga %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_ga_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "GA",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_ga_2021 <- census_data_ga_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_ga_2021 <- census_data_ga_2021 %>%
  mutate(state = case_when(
    state == 'Georgia' ~ "GA")) %>%
  mutate(city = case_when(
    city == 'Athens-Clarke County unified government (balance)' ~ "Athens",
    city == 'Macon-Bibb County' ~ "Macon",
    city == 'McRae-Helena' ~ 'McRae',
    TRUE ~ city))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_ga_complete <- distinct_hometowns_ga %>%
  left_join(census_data_ga_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_ga_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Ellenwood, GA, the zip code (30294) seems to be a good substitute: https://censusreporter.org/profiles/86000US30294-30294/
census_data_ellenwood_ga_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 30294") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "GA") %>%
  mutate(city = case_when(
    city == "ZCTA5 30294" ~ "Ellenwood")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# For Rabun Gap, GA, the zip code (30568) seems to be a good substitute: https://censusreporter.org/profiles/86000US30568-30568/
census_data_rabun_ga_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 30568") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "GA") %>%
  mutate(city = case_when(
    city == "ZCTA5 30568" ~ "Rabun Gap")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# For Rex, GA, the zip code (30273) seems to be a good substitute: https://censusreporter.org/profiles/86000US30273-30273/
census_data_rex_ga_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 30273") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "GA") %>%
  mutate(city = case_when(
    city == "ZCTA5 30273" ~ "Rex")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# For Subligna, GA, the block group seems to be a good substitute: https://censusreporter.org/profiles/15000US130550101002-bg-2-tract-101-chattooga-ga/
census_data_subligna_ga_2021 <- get_acs(geography = "block group",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "GA",
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "Block Group 2, Census Tract 101, Chattooga County, Georgia") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "GA") %>%
  mutate(city = case_when(
    city == "Block Group 2, Census Tract 101, Chattooga County, Georgia" ~ "Subligna")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_ga_2021 <- bind_rows(census_data_ga_2021, census_data_ellenwood_ga_2021, census_data_rabun_ga_2021, census_data_rex_ga_2021, census_data_subligna_ga_2021)

hometowns_ga_complete <- distinct_hometowns_ga %>%
  left_join(census_data_ga_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_ga_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_ga_complete, file = "hometowns_ga.csv")

```

```{r}

# HAWAII HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_hi <- football_rosters_usa %>%
  filter(hometown_state_clean == "HI")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_hi <- football_rosters_hi %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_hi_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "HI",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_hi_2021 <- census_data_hi_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_hi_2021 <- census_data_hi_2021 %>%
  mutate(state = case_when(
    state == 'Hawaii' ~ "HI")) %>%
  mutate(city = case_when(
    city == 'Urban Honolulu' ~ "Honolulu",
    city == 'Kailua (Honolulu County)' ~ "Kailua",
    city == 'Kapaa' ~ "Kapa'a",
    city == "Mililani Town" ~ "Mililani",
    TRUE ~ city))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_hi_complete <- distinct_hometowns_hi %>%
  left_join(census_data_hi_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_hi_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Hawaii, we fixed all the NA values by adjusting the way the census referred to the town (see Step 5) or by adjusting the player's hometown name in OpenRefine (for example, players whose hometowns were listed as Maui)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.

# N/A for Hawaii

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_hi_complete, file = "hometowns_hi.csv")

```

```{r}

# IOWA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_ia <- football_rosters_usa %>%
  filter(hometown_state_clean == "IA")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_ia <- football_rosters_ia %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_ia_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "IA",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_ia_2021 <- census_data_ia_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_ia_2021 <- census_data_ia_2021 %>%
  mutate(state = case_when(
    state == 'Iowa' ~ "IA"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_ia_complete <- distinct_hometowns_ia %>%
  left_join(census_data_ia_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_ia_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# Pleasant Valley, IA is a county subdivision: https://censusreporter.org/profiles/06000US1916393420-pleasant-valley-township-scott-county-ia/
census_data_pleasant_ia_2021 <- get_acs(geography = "county subdivision",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "Iowa",
                           county = "Scott County",
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "Pleasant Valley township, Scott County, Iowa") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "IA") %>%
  mutate(city = case_when(
    city == "Pleasant Valley township, Scott County, Iowa" ~ "Pleasant Valley")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_ia_2021 <- bind_rows(census_data_ia_2021, census_data_pleasant_ia_2021)
 
hometowns_ia_complete <- distinct_hometowns_ia %>%
  left_join(census_data_ia_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_ia_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_ia_complete, file = "hometowns_ia.csv")

```

```{r}

# LOUISIANA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_la <- football_rosters_usa %>%
  filter(hometown_state_clean == "LA")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_la <- football_rosters_la %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_la_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "LA",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_la_2021 <- census_data_la_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_la_2021 <- census_data_la_2021 %>%
  mutate(state = case_when(
    state == 'Louisiana' ~ "LA"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_la_complete <- distinct_hometowns_la %>%
  left_join(census_data_la_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_la_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Geismar, LA (70734), St. Amant, LA (70774), and Vacherie, LA (70090), the zip codes seems to be good substitutes: https://censusreporter.org/profiles/86000US70734-70734/ https://censusreporter.org/profiles/86000US70774-70774/ https://censusreporter.org/profiles/86000US70090-70090/
census_data_zips_la_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 70734" | name == "ZCTA5 70774" | name == "ZCTA5 70090") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "LA") %>%
  mutate(city = case_when(
    city == "ZCTA5 70734" ~ "Geismar",
    city == "ZCTA5 70774" ~ "St. Amant",
    city == "ZCTA5 70090" ~ "Vacherie")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_la_2021 <- bind_rows(census_data_la_2021, census_data_zips_la_2021)
 
hometowns_la_complete <- distinct_hometowns_la %>%
  left_join(census_data_la_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_la_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_la_complete, file = "hometowns_la.csv")

```

```{r}

# MARYLAND HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_md <- football_rosters_usa %>%
  filter(hometown_state_clean == "MD")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_md <- football_rosters_md %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_md_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "MD",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_md_2021 <- census_data_md_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_md_2021 <- census_data_md_2021 %>%
  mutate(state = case_when(
    state == 'Maryland' ~ "MD"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_md_complete <- distinct_hometowns_md %>%
  left_join(census_data_md_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_md_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Clarksville, MD (21029), Davidsonville, MD (21035), Ijamsville, MD (21770), Phoenix, MD (21131) the zip codes seem to be good substitutes: https://censusreporter.org/profiles/86000US21029-21029/ https://censusreporter.org/profiles/86000US21035-21035/ https://censusreporter.org/profiles/86000US21770-21770/ https://censusreporter.org/profiles/86000US21131-21131/
census_data_zips_md_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 21029" | name == "ZCTA5 21035" | name == "ZCTA5 21770" | name == "ZCTA5 21131") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "MD") %>%
  mutate(city = case_when(
    city == "ZCTA5 21029" ~ "Clarksville",
    city == "ZCTA5 21035" ~ "Davidsonville",
    city == "ZCTA5 21770" ~ "Ijamsville",
    city == "ZCTA5 21131" ~ "Phoenix")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_md_2021 <- bind_rows(census_data_md_2021, census_data_zips_md_2021)
 
hometowns_md_complete <- distinct_hometowns_md %>%
  left_join(census_data_md_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_md_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_md_complete, file = "hometowns_md.csv")

```

```{r}

# MISSISSIPPI HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_ms <- football_rosters_usa %>%
  filter(hometown_state_clean == "MS")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_ms <- football_rosters_ms %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_ms_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "MS",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_ms_2021 <- census_data_ms_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_ms_2021 <- census_data_ms_2021 %>%
  mutate(state = case_when(
    state == 'Mississippi' ~ "MS"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_ms_complete <- distinct_hometowns_ms %>%
  left_join(census_data_ms_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_ms_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Nesbit, MS, the zip code (38651) seems to be a good substitute: https://censusreporter.org/profiles/86000US38651-38651/
census_data_nesbit_ms_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 38651") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "MS") %>%
  mutate(city = case_when(
    city == "ZCTA5 38651" ~ "Nesbit")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# For Friendship, MS data obtained using population of nearby Collins, MS, where the player went to HS https://censusreporter.org/profiles/16000US2815140-collins-ms/
census_data_friendship_ms_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "MS",
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "Collins city, Mississippi") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "MS") %>%
  mutate(city = case_when(
    city == "Collins city, Mississippi" ~ "Friendship")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_ms_2021 <- bind_rows(census_data_ms_2021, census_data_nesbit_ms_2021, census_data_friendship_ms_2021)
 
hometowns_ms_complete <- distinct_hometowns_ms %>%
  left_join(census_data_ms_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_ms_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_ms_complete, file = "hometowns_ms.csv")

```

```{r}

# NEBRASKA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_ne <- football_rosters_usa %>%
  filter(hometown_state_clean == "NE")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_ne <- football_rosters_ne %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_ne_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "NE",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_ne_2021 <- census_data_ne_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_ne_2021 <- census_data_ne_2021 %>%
  mutate(state = case_when(
    state == 'Nebraska' ~ "NE"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_ne_complete <- distinct_hometowns_ne %>%
  left_join(census_data_ne_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_ne_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.
# Not applicable because no NA values for Nebraska

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
# Not applicable because no NA values for Nebraska

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_ne_complete, file = "hometowns_ne.csv")

```
```{r}

# NORTH CAROLINA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_nc <- football_rosters_usa %>%
  filter(hometown_state_clean == "NC")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_nc <- football_rosters_nc %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_nc_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "NC",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_nc_2021 <- census_data_nc_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_nc_2021 <- census_data_nc_2021 %>%
  mutate(state = case_when(
    state == 'North Carolina' ~ "NC"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_nc_complete <- distinct_hometowns_nc %>%
  left_join(census_data_nc_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_nc_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Arden, NC (28704), the zip code seems to be good substitutes: https://censusreporter.org/profiles/86000US28704-28704/
census_data_arden_nc_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 28704") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "NC") %>%
  mutate(city = case_when(
    city == "ZCTA5 28704" ~ "Arden")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_nc_2021 <- bind_rows(census_data_nc_2021, census_data_arden_nc_2021)
 
hometowns_nc_complete <- distinct_hometowns_nc %>%
  left_join(census_data_nc_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_nc_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_nc_complete, file = "hometowns_nc.csv")

```
```{r}

# OHIO HOMETOWNS (not the best one to use as a template) - IN PROGRESS; this one is a mess, refer to notepad for ideas on how to tackle it

# Step 1: Filter for the state's players
football_rosters_oh <- football_rosters_usa %>%
  filter(hometown_state_clean == "OH")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_oh <- football_rosters_oh %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_oh_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "OH",
                           output = "wide")

# It turns out that many towns in Ohio are county subdivisions, so we will grab some of those we need, too
census_data_oh_subdivisions_2021 <- get_acs(geography = "county subdivision",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "OH",
                           output = "wide") %>%
  filter(NAME == "Braceville township, Trumbull County, Ohio" | NAME == "Colerain township, Hamilton County, Ohio" | NAME == "Concord township, Lake County, Ohio" | NAME == "Liberty township, Butler County, Ohio" | NAME == "West Chester township, Butler County, Ohio")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_oh_2021 <- census_data_oh_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

census_data_oh_subdivisions_2021 <- census_data_oh_subdivisions_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "county", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village|municipality|township)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

census_data_oh_2021 <- bind_rows(census_data_oh_2021, census_data_oh_subdivisions_2021)

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_oh_2021 <- census_data_oh_2021 %>%
  mutate(state = case_when(
    state == 'Ohio' ~ "OH")) %>%
  mutate(city = case_when(
    city == "Liberty" ~ "Liberty Township",
    TRUE ~ city))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_oh_complete <- distinct_hometowns_oh %>%
  left_join(census_data_oh_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_oh_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Lewis Center, OH (43035) and North Jackson, OH (44451), the zip codes seems to be good substitutes: https://censusreporter.org/profiles/86000US43035-43035/ https://censusreporter.org/profiles/86000US44451-44451/
census_data_zips_oh_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 43035" | name == "ZCTA5 44451") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "OH") %>%
  mutate(city = case_when(
    city == "ZCTA5 43035" ~ "Lewis Center",
    city == "ZCTA5 44451" ~ "North Jackson")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_oh_2021 <- bind_rows(census_data_oh_2021, census_data_zips_oh_2021)
 
hometowns_oh_complete <- distinct_hometowns_oh %>%
  left_join(census_data_oh_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_oh_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_oh_complete, file = "hometowns_oh.csv")

```


```{r}

# SOUTH CAROLINA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_sc <- football_rosters_usa %>%
  filter(hometown_state_clean == "SC")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_sc <- football_rosters_sc %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_sc_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "SC",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_sc_2021 <- census_data_sc_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_sc_2021 <- census_data_sc_2021 %>%
  mutate(state = case_when(
    state == 'South Carolina' ~ "SC"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_sc_complete <- distinct_hometowns_sc %>%
  left_join(census_data_sc_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_sc_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Craytonville, SC, the block group seems to be a good substitute: https://censusreporter.org/profiles/15000US450070115013-bg-3-tract-11501-anderson-sc/
census_data_craytonville_sc_2021 <- get_acs(geography = "block group",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "SC",
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "Block Group 3, Census Tract 115.01, Anderson County, South Carolina") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "SC") %>%
  mutate(city = case_when(
    city == "Block Group 3, Census Tract 115.01, Anderson County, South Carolina" ~ "Craytonville")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_sc_2021 <- bind_rows(census_data_sc_2021, census_data_craytonville_sc_2021)
 
hometowns_sc_complete <- distinct_hometowns_sc %>%
  left_join(census_data_sc_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_sc_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_sc_complete, file = "hometowns_sc.csv")

```

```{r}

# TEXAS HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_tx <- football_rosters_usa %>%
  filter(hometown_state_clean == "TX")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_tx <- football_rosters_tx %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_tx_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "TX",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_tx_2021 <- census_data_tx_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_tx_2021 <- census_data_tx_2021 %>%
  mutate(state = case_when(
    state == 'Texas' ~ "TX")) %>%
  filter(city != "Mesquite" | total_pop != 181) #Removing the second Mesquite, TX that is a CDP

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_tx_complete <- distinct_hometowns_tx %>%
  left_join(census_data_tx_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_tx_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Cypress, TX (77429), New Caney, TX (77357), and Wall, TX (76957), the zip codes seems to be good substitutes: https://censusreporter.org/profiles/86000US77429-77429/ https://censusreporter.org/profiles/86000US77357-77357/ https://censusreporter.org/profiles/86000US76957-76957/
census_data_zips_tx_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 77429" | name == "ZCTA5 77357" | name == "ZCTA5 76957") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "TX") %>%
  mutate(city = case_when(
    city == "ZCTA5 77429" ~ "Cypress",
    city == "ZCTA5 77357" ~ "New Caney",
    city == "ZCTA5 76957" ~ "Wall")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# For Brock, TX, and Klein, TX, used the school districts because all players went to the same high school: https://censusreporter.org/profiles/97000US4811460-brock-independent-school-district-tx/ https://censusreporter.org/profiles/97000US4825740-klein-independent-school-district-tx/ 
census_data_sd_tx_2021 <- get_acs(geography = "school district (unified)",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "TX",
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "Brock Independent School District, Texas" | name == "Klein Independent School District, Texas") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "TX") %>%
  mutate(city = case_when(
    city == "Brock Independent School District, Texas" ~ "Brock",
    city == "Klein Independent School District, Texas" ~ "Klein")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_tx_2021 <- bind_rows(census_data_tx_2021, census_data_zips_tx_2021, census_data_sd_tx_2021)
 
hometowns_tx_complete <- distinct_hometowns_tx %>%
  left_join(census_data_tx_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_tx_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_tx_complete, file = "hometowns_tx.csv")

```

```{r}

# UTAH HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_ut <- football_rosters_usa %>%
  filter(hometown_state_clean == "UT")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_ut <- football_rosters_ut %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_ut_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "UT",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_ut_2021 <- census_data_ut_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_ut_2021 <- census_data_ut_2021 %>%
  mutate(state = case_when(
    state == 'Utah' ~ "UT")) %>%
  mutate(city = case_when(
    city == 'Heber' ~ "Heber City",
    TRUE ~ city))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_ut_complete <- distinct_hometowns_ut %>%
  left_join(census_data_ut_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_ut_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.
# In this case, there was a discrepancy between our hometown data, which had a city named Heber City, and the census data, which referred to that town as Heber. We fixed it by going back to Step #5 and adding in a case_when statement for Heber.

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
# Not applicable for Utah

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_ut_complete, file = "hometowns_ut.csv")

```
```{r}

# VIRGINIA HOMETOWNS

# Step 1: Filter for the state's players
football_rosters_va <- football_rosters_usa %>%
  filter(hometown_state_clean == "VA")

# Step 2: Get a list of all the unique hometowns in the state
distinct_hometowns_va <- football_rosters_va %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Step 3: Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_va_2021 <- get_acs(geography = "place",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "VA",
                           output = "wide")

# Step 4: General cleaning of census data to prepare for join with hometowns/roster data. This part is the same for every state and (except for the dataframe name) can more or less be copied and pasted.
census_data_va_2021 <- census_data_va_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

# Step 5: State-specific cleaning of census data to prepare for join with hometowns/roster data. This part is different for every state. The first mutate function should be included for every state, just modified depending on the state name. Additional mutate functions may be needed for instances when the census names something in a weird way that doesn't line up with the hometowns.
census_data_va_2021 <- census_data_va_2021 %>%
  mutate(state = case_when(
    state == 'Virginia' ~ "VA"))

# Step 6: Join the census data to the list of hometowns. Also create a column that tells us how many people are elite college football players for every 1,000 residents.
hometowns_va_complete <- distinct_hometowns_va %>%
  left_join(census_data_va_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Step 7: Notice there are a few NA values. This happens when the census data does not join with the hometowns data, perhaps because the hometown is misspelled or because there is no census data for that town. First, let's find the NA values.
hometowns_va_complete %>%
  filter(is.na(geoid))

# Step 8: Now we have to figure out how to address each of the NA values. This is a judgment call, and we should be careful about documenting how and why we made that decision. If there is an NA value because a hometown is misspelled, tell Sapna, and she will make that correction in Open Refine. If there is an NA value because the census does not recognize the hometown, we need to find some substitute for that hometown.

# For Aylett, VA (23009), Bristow, VA (20136), Hayes, VA (23072), Oak Hill, VA (22030), and Chesterfield, VA (23832) the zip codes seems to be good substitutes: https://censusreporter.org/profiles/86000US23009-23009/ https://censusreporter.org/profiles/86000US20136-20136/ https://censusreporter.org/profiles/86000US23072-23072/ https://censusreporter.org/profiles/86000US22030-22030/ https://censusreporter.org/profiles/86000US23832-23832/
census_data_zips_va_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 23009" | name == "ZCTA5 20136" | name == "ZCTA5 23072" | name == "ZCTA5 22030" | name == "ZCTA5 23832") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "VA") %>%
  mutate(city = case_when(
    city == "ZCTA5 23009" ~ "Aylett",
    city == "ZCTA5 20136" ~ "Bristow",
    city == "ZCTA5 23072" ~ "Hayes",
    city == "ZCTA5 22030" ~ "Oak Hill",
    city == "ZCTA5 23832" ~ "Chesterfield")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Browns Store, VA is a county subdivision: https://censusreporter.org/profiles/06000US1916393420-pleasant-valley-township-scott-county-ia/
census_data_browns_va_2021 <- get_acs(geography = "county subdivision",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = "Virginia",
                           county = "Lunenburg County",
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "Browns Store district, Lunenburg County, Virginia") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "VA") %>%
  mutate(city = case_when(
    city == "Browns Store district, Lunenburg County, Virginia" ~ "Browns Store")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# Step 9: We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_va_2021 <- bind_rows(census_data_va_2021, census_data_zips_va_2021, census_data_browns_va_2021)
 
hometowns_va_complete <- distinct_hometowns_va %>%
  left_join(census_data_va_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

hometowns_va_complete %>%
  filter(is.na(geoid)) #If this is not producing an empty dataframe, go back and continue to work on NA values

# Step 10: If needed, uncomment out to create a CSV
#write_csv(hometowns_va_complete, file = "hometowns_va.csv")

```


```{r}

# SMALLER STATE HOMETOWNS - use for all states with less than 50 Power Five players (WY, AK, RI, ND, NH, MT, NM, SD, DE, ID, DC, WV, CT, NV); *do not use this as a template*

# Vector of all states with fewer than 50 players
states_under_50 <- football_rosters_usa_states$hometown_state_clean[football_rosters_usa_states$total_players < 50]

# Filter for the states' players
football_rosters_small_states <- football_rosters_usa %>%
  filter(hometown_state_clean %in% states_under_50)

# Get a list of all the unique hometowns in the state
distinct_hometowns_small_states <- football_rosters_small_states %>%
  group_by(hometown_city_clean, hometown_state_clean) %>%
  summarise(total_players = n())

# Grab the relevant census data for that state. Note: B01003 = total population, B02001 = total Black population, B19013 = median household income. We get these codes using the ACS crosswalk we loaded earlier (ACS_2001) and this website: https://censusreporter.org/topics/table-codes/
census_data_small_states_2021 <- lapply(states_under_50, function(state) {
  get_acs(geography = "place",
          variables = c("B01003_001", "B02001_003", "B19013_001"),
          year = 2021,
          state = state,
          output = "wide")
})

census_data_small_states_2021 <- do.call(rbind, census_data_small_states_2021)

# It turns out that many towns in Connecticut, New Hampshire, and Rhode Island are county subdivisions, so we will grab those, too
census_data_small_states_subdivisions_2021 <- get_acs(geography = "county subdivision",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           state = c("CT", "NH", "RI"),
                           output = "wide")

# General cleaning of census data to prepare for join with hometowns/roster data.
census_data_small_states_2021 <- census_data_small_states_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village|municipality)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

census_data_small_states_subdivisions_2021 <- census_data_small_states_subdivisions_2021 %>%
  clean_names() %>%
  separate(name, into = c("city", "county", "state"), sep = ", ", remove = FALSE) %>%
  mutate(city = gsub("\\b(town|city|CDP|village|municipality)\\b", "", city)) %>%
  mutate(city = str_squish(city)) %>%
  select(geoid, city, state, b01003_001e, b02001_003e, b19013_001e) %>%
  rename(total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1))

census_data_small_states_2021 <- bind_rows(census_data_small_states_2021, census_data_small_states_subdivisions_2021)

# Cleaning of census data to prepare for join with hometowns/roster data.
state_crosswalk_modified <- state_crosswalk %>%
  mutate(state_names = str_to_title(state_name_caps)) %>%
  mutate(state_names = case_when(
    state_names == 'Washington, Dc' ~ "District of Columbia",
    TRUE ~ state_names)) %>%
  select(state_abb, state_names)

census_data_small_states_2021 <- census_data_small_states_2021 %>%
  left_join(state_crosswalk_modified, by = c("state" = "state_names")) %>%
  mutate(state = census_data_small_states_2021$state_abb) %>% 
  mutate(city = case_when(
    city == 'Boise City' ~ "Boise",
    TRUE ~ city))

census_data_small_states_2021 <- census_data_small_states_2021 %>%
  rename(state = state_abb)

# Join the census data to the list of hometowns.
hometowns_small_states_complete <- distinct_hometowns_small_states %>%
  left_join(census_data_small_states_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# Now we have to figure out how to address each of the NA values.
# For Ona, WV, the zip code (25545) seems to be a good substitute: https://censusreporter.org/profiles/86000US25545-25545/
census_data_ona_wv_2021 <- get_acs(geography = "zcta",
                           variables = c("B01003_001", "B02001_003", "B19013_001"),
                           year = 2021,
                           output = "wide") %>%
  clean_names() %>%
  filter(name == "ZCTA5 25545") %>%
  rename(city = name, total_pop = b01003_001e, black_pop = b02001_003e, median_income = b19013_001e) %>%
  mutate(pct_black = round(black_pop/total_pop*100, 1)) %>%
  mutate(state = "WV") %>%
  mutate(city = case_when(
    city == "ZCTA5 25545" ~ "Ona")) %>%
  select(geoid, city, state, total_pop, black_pop, median_income, pct_black)

# We now have to append these special cases to our state census data, redo the join, and run one more check for NA values.
census_data_small_states_2021 <- bind_rows(census_data_small_states_2021, census_data_ona_wv_2021)
 
hometowns_small_states_complete <- distinct_hometowns_small_states %>%
  left_join(census_data_small_states_2021, by = c("hometown_city_clean" = "city", "hometown_state_clean" = "state")) %>%
  mutate(players_per_thousand = round((total_players*1000)/total_pop,1)) %>%
  arrange(desc(players_per_thousand))

# If needed, uncomment out to create a CSV
#write_csv(hometowns_small_states_complete, file = "hometowns_small_states.csv")

```

```{r}

# ALL HOMETOWNS
hometowns_complete <- bind_rows(hometowns_al_complete, hometowns_az_complete, hometowns_fl_complete, hometowns_ga_complete, hometowns_hi_complete, hometowns_ia_complete, hometowns_la_complete, hometowns_md_complete, hometowns_ms_complete, hometowns_nc_complete, hometowns_ne_complete, hometowns_oh_complete, hometowns_sc_complete, hometowns_tx_complete, hometowns_ut_complete, hometowns_va_complete, hometowns_small_states_complete) %>%
  mutate(hometown_combined = paste(hometown_city_clean, hometown_state_clean, sep = ", ")) %>%
  arrange(desc(players_per_thousand)) %>%
  select(hometown_city_clean:hometown_state_clean, hometown_combined, total_players:players_per_thousand)

#write_csv(hometowns_complete, file = "hometowns_complete.csv")

```

```{r}

# OTHER - use for messing around

distribution <- hometowns_complete %>%
  group_by(total_players) %>%
  summarise(total = n())

five_plus <- hometowns_complete %>%
  filter(total_players >= 5) %>%
  arrange(desc(players_per_thousand))

#write_csv(five_plus, file = "five_plus_players.csv")

```